### PR TITLE
Completed the Mint Sign Up form

### PR DESCRIPTION
**Pull request by Cyrus-Kiprop**
My pairing partner and I, just finished the Mint sign up form clone exercise project and we would like to request for a project code review for this particular pull request. Thank you.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
## Hi team :clap: 

### :+1: Good job so far, however you need to take care of the following:
- The mid section of your form is not well aligned;
image
And take note that all labels should appear above the input field as is in the original.

- **Optional:** Add href attribute to the anchor tags for these links : _Terms, Privacy Statement, Google Privacy Policy and Terms of Use_.

**Kindly make these changes and submit another code review request**

**Happy coding!**

**Status: Changes requested**

**Comment by Cyrus-Kiprop** [comment]
@mosesogwo all requested changes have been resolved. Thank you.

**Comment by mosesogwo** [comment]
## Hi @Cyrus-Kiprop, @zubiix 
I'm sorry about my earlier review.
I just found out that for some strange reason, Firefox is not displaying pages for me properly. The mid section of the form is well aligned on other browsers.

Kindly submit another code review request for your pull request.

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!
### Wow! The project looks really very good! The readme file is so descriptive! :+1:  
*  I hope these links can help make your readme file more professional in the next projects [Professional Github repository](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) and this [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

✔️ Approved

* Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/).  I hope in the next project you can do this! 

### You can merge it and don't forget to fill the project completion form..

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
